name: Publish on NuGet

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
        
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.6.0
      with:
        dotnet-version: 3.1.402
        
    - name: Nerdbank.GitVersioning 
      uses: dotnet/nbgv@v0.3.1
      id: nbgv
      with:        
        path: TinyNetHelpers     
        
    - name: Print output    
      run: echo ${{ steps.nbgv.outputs.NuGetPackageVersion }}
