name: Publish Tiny .NET Helpers on NuGet
 
on:
  push:
    branches: [ master ]
    paths: [ 'src/TinyHelpers/**' ]
  workflow_dispatch:

env:
  NETCORE_VERSION: '5.0.202'
  PROJECT_NAME: src/TinyHelpers 
  PROJECT_FILE: TinyHelpers.csproj
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    name: Publish on NuGet
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
        
    - name: Setup .NET Core SDK ${{ env.NETCORE_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}
        
    - name: Publish on NuGet        
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:          
        PROJECT_FILE_PATH: '${{ env.PROJECT_NAME }}/${{ env.PROJECT_FILE }}'
        TAG_FORMAT: v*
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
