name: Publish on NuGet

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Nerdbank.GitVersioning 
      uses: dotnet/nbgv@v0.3.1
      with:
        # The path to the directory for which the version should be determined. This should be at or below the directory containing the version.json file. Default is repo root directory.
        path: TinyNetHelpers
    - run: echo 'SemVer2: ${{ steps.nbgv.outputs.SemVer2 }}'
